<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TI49TLR" failures="0" tests="5" name="practicetestng.TestNgExceptionExample" time="0.033" errors="0" timestamp="2023-07-06T12:38:12 IST" skipped="0">
  <testcase classname="practicetestng.TestNgExceptionExample" name="createCustomer" time="0.003"/>
  <system-out>
    <![CDATA[createCustomer]]>
  </system-out>
  <testcase classname="practicetestng.TestNgExceptionExample" name="createCustomer" time="0.005"/>
  <system-out>
    <![CDATA[createCustomer]]>
  </system-out>
  <testcase classname="practicetestng.TestNgExceptionExample" name="createCustomer" time="0.007"/>
  <system-out>
    <![CDATA[createCustomer]]>
  </system-out>
  <testcase classname="practicetestng.TestNgExceptionExample" name="modifyCustomer" time="0.013"/>
  <system-out>
    <![CDATA[modifyCustomer]]>
  </system-out>
  <testcase classname="practicetestng.TestNgExceptionExample" name="deleteCustomer" time="0.005"/>
  <system-out>
    <![CDATA[deleteCustomer]]>
  </system-out>
</testsuite> <!-- practicetestng.TestNgExceptionExample -->
